name: Build and Push Docker Image for Client

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_TAG: client-1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile-Client
        push: true
        tags: hyperxpro/streamsockets:${{ env.DOCKER_TAG }}
